name: Deploy

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17 for x64
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'
          architecture: x64
      - name: Build with Maven
        run: mvn clean package
      # Setup key
      - run: set -eu
      - run: mkdir "$HOME/.ssh"
      - run: echo "${{ secrets.key }}" > "$HOME/.ssh/key"
      - run: chmod 600 "$HOME/.ssh/key"

      # Stop the old application
      - name: Stop old application
        run: ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no admin@87.242.85.251 "lsof -t -i :8081 | xargs kill -9 || true"

      # Deploy
      - name: Deploy new application
        run: |
          rsync -e "ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete target/botFood-3.2.4.jar admin@87.242.85.251:/home/admin/currency-bot
          ssh -i $HOME/.ssh/key -o StrictHostKeyChecking=no admin@87.242.85.251 "/home/admin/currency-bot/start.sh"